version: "3.3"
services:

  web:
    restart: always
    image: staticpages_web_1
    expose:
      - "5000"

  nginx:
    restart: always
    image: staticpages_nginx_1
    ports:
      - "0.0.0.0:8888:80"
    volumes:
      - /www/static
    links:
      - web:web
