web:
  restart: always
  build: .
  expose:
    - "5000"
  volumes:
    - /usr/src/app/static

nginx:
  restart: always
  build: ./nginx
  ports:
    - "127.0.0.1:8080:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web